const GET_TODO_REQUEST = 'GET_TODO_REQUEST'
const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
const GET_TODO_FAILURE = 'GET_TODO_FAILURE'

const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

const IND_GET_TODO_REQUEST = 'IND_GET_TODO_REQUEST'
const IND_GET_TODO_SUCCESS = 'IND_GET_TODO_SUCCESS'
const IND_GET_TODO_FAILURE = 'IND_GET_TODO_FAILURE'

const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST'
const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'
const TOGGLE_TODO_FAILURE = 'TOGGLE_TODO_FAILURE'

const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

const UPDATE_TODO_TITLE_REQUEST = 'UPDATED_TODO_TITLE_REQUEST'
const UPDATE_TODO_TITLE_SUCCESS = 'UPDATED_TODO_TITLE_SUCCESS'
const UPDATE_TODO_TITLE_FAILURE = 'UPDATED_TODO_TITLE_FAILURE'

export { GET_TODO_REQUEST,
         GET_TODO_SUCCESS,
         GET_TODO_FAILURE,

         ADD_TODO_REQUEST,
         ADD_TODO_SUCCESS,
         ADD_TODO_FAILURE, 

         IND_GET_TODO_REQUEST, 
         IND_GET_TODO_SUCCESS, 
         IND_GET_TODO_FAILURE,

         TOGGLE_TODO_REQUEST,
         TOGGLE_TODO_SUCCESS,
         TOGGLE_TODO_FAILURE,

         DELETE_TODO_REQUEST,
         DELETE_TODO_SUCCESS,
         DELETE_TODO_FAILURE,
        
         UPDATE_TODO_TITLE_REQUEST,
         UPDATE_TODO_TITLE_SUCCESS,
         UPDATE_TODO_TITLE_FAILURE}