export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const DELETE_TODO = "DELETE_TODO";

// get Todo Requests
const GET_TODO_REQUEST = "GET_TODO_REQUEST";
const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
const GET_TODO_FAILURE = "GET_TODO_FAILURE";

export { ADD_TODO, TOGGLE_TODO, DELETE_TODO, GET_TODO_REQUEST, GET_TODO_SUCCESS, GET_TODO_FAILURE }