const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

const GET_TODO_REQUEST = 'GET_TODO_REQUEST'
const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS'
const GET_TODO_FAILURE = 'GET_TODO_FAILURE'

export { ADD_TODO_REQUEST,
         ADD_TODO_SUCCESS,
         ADD_TODO_FAILURE,

         GET_TODO_REQUEST,
         GET_TODO_SUCCESS,
         GET_TODO_FAILURE }