import axios from 'axios';

const REGISTER_REQUEST = 'REGISTER_REQUEST';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';

const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const USER_REGISTERED_DETAILS_REQUEST = 'USER_REGISTERED_DETAILS_REQUEST';
const USER_REGISTERED_DETAILS_SUCCESS = 'USER_REGISTERED_DETAILS_SUCCESS';
const USER_REGISTERED_DETAILS_FAILURE = 'USER_REGISTERED_DETAILS_FAILURE';

const GITHUB_SEARCH_REQUEST = 'GITHUB_SEARCH_REQUEST';
const GITHUB_SEARCH_SUCCESS = 'GITHUB_SEARCH_SUCCESS';
const GITHUB_SEARCH_FAILURE = 'GITHUB_SEARCH_FAILURE';

export { REGISTER_REQUEST, 
         REGISTER_SUCCESS,
         REGISTER_FAILURE, 

         LOGIN_REQUEST, 
         LOGIN_SUCCESS, 
         LOGIN_FAILURE, 

         USER_REGISTERED_DETAILS_REQUEST,
         USER_REGISTERED_DETAILS_SUCCESS,
         USER_REGISTERED_DETAILS_FAILURE,

         GITHUB_SEARCH_REQUEST, 
         GITHUB_SEARCH_SUCCESS, 
         GITHUB_SEARCH_FAILURE }