const INCREMENT_COUNTER = "INCREMENT_COUNTER";
const DECREMENT_COUNTER = "DECREMENT_COUNTER";

const ADD_NUM = "ADD_NUM";
const SUBTRACT_NUM = "SUBTRACT_NUM";
const MULTIPLY_NUM = "MULTIPLY_NUM";
const DIVIDE_NUM = "DIVIDE_NUM";

export {INCREMENT_COUNTER, DECREMENT_COUNTER, ADD_NUM, SUBTRACT_NUM, MULTIPLY_NUM, DIVIDE_NUM}